### ISSUE TITLE
Для каждого пользователя "свой" собственный пароль

### ISSUE THREAD

**Issue by qertis** [tewst/ProstoDiary_bot#1]
При /start будет генерироваться пароль пользователя на основе account.name + account.firstname + ...
Пользователю будет выдаваться этот пароль на случай чтобы не забыл. 

Затем если пользователю захочется выполнить /download или /dbclear будет требоваться этот пароль для подтверждение

**Comment by baskovsky** [comment]
Учитывая https://github.com/tewst/ProstoDiary_bot/issues/16 и self-install решения, пароль будет хранится только в env
