### ISSUE TITLE
Изменить вхождения в вызовах /graph 

### ISSUE THREAD

**Issue by qertis** [tewst/ProstoDiary_bot#17]
Сейчас работает простая функция include. Нужна регулярка.

Например, при поиске 'е' будет искатся вхождение:
'^е '
' е '
' е$'
'^е$'

**Comment by baskovsky** [comment]
Пример запроса вхождения b
```js
x = new RegExp('( b )|( b$)|(^b )|(^b$)')
```

**Comment by qertis** [comment]
cbdf08f26bb32a37442047b068895bc635f1fe74
